### ISSUE TITLE
能把使用方法再讲解一下吗,多谢

### ISSUE THREAD

**Issue by 9ihbd2DZSMjtsf7vecXjz** [loozzi/bot_telegram#1]

**Comment by loozzi** [comment]
1. Install python from the official website.
2. Clone this repository
3. Install the package by running the command: `pip install -r requirements.txt`
4. Create bot by sending a message to channel [@Botfather](https://t.me/BotFather) and getthe key
5. Create a file named `.env` in the root folder with following content: `TOKEN=<YOUR KEY>`
6. Run bot by executing command: `python bot.py`

Do you have any more questions?
