### ISSUE TITLE
Douyin Link

### ISSUE THREAD

**Issue by zuijiaoshangyang2** [loozzi/bot_telegram#2]
The sharing link of Douyin mobile app is usually like this:  
4.84 复制打开抖音，看看【大头呢呢呢呢的作品】# 召唤猫术 # 混的猫 # 暗中观察 # 猫猫侠... https://v.douyin.com/iMN75MLs/ 09/02 NWM:/ S@Y.zt
The sharing link on the computer web page looks like this：
9.97 Mjc:/ U@L.JI 09/18 与我一起掉入童话世界 # 童话镇慢动作  https://v.douyin.com/iMN77Yvu/ 复制此链接，打开Dou音搜索，直接观看视频！

only https://v.douyin.com/iMN75MLs/  or https://v.douyin.com/iMN77Yvu/   can be correctly identified.  So it would be nice if it could process the shared link before parsing, although we can manually delete the useless parts.

**Comment by loozzi** [comment]
@zuijiaoshangyang2 i've updated

**Comment by zuijiaoshangyang2** [comment]
Thank you for your excellent work！This is more convenient.
